In [2]:
import pandas as pd 
import numpy as np

In [3]:
df=pd.read_csv("data.csv")

In [4]:
df.head()

,age,gender,tot_bilirubin,direct_bilirubin,tot_proteins,albumin,ag_ratio,sgpt,sgot,alkphos,is_patient
0,65,Female,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,Male,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               583 non-null    int64
 1   gender            583 non-null    str
 2   tot_bilirubin     583 non-null    float64
 3   direct_bilirubin  583 non-null    float64
 4   tot_proteins      583 non-null    int64
 5   albumin           583 non-null    int64
 6   ag_ratio          583 non-null    int64
 7   sgpt              583 non-null    float64
 8   sgot              583 non-null    float64
 9   alkphos           579 non-null    float64
 10  is_patient        583 non-null    int64
dtypes: float64(5), int64(5), str(1)
memory usage: 50.2 KB

In [7]:
df.shape

(583, 11)

In [8]:
print(df.duplicated().sum())

13

In [9]:
df = df.drop_duplicates()

In [10]:
print(df.duplicated().sum())

0

In [13]:
df = pd.get_dummies(df, columns=["gender"])

In [14]:
df.info()

<class 'pandas.DataFrame'>
Index: 570 entries, 0 to 582
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               570 non-null    int64
 1   tot_bilirubin     570 non-null    float64
 2   direct_bilirubin  570 non-null    float64
 3   tot_proteins      570 non-null    int64
 4   albumin           570 non-null    int64
 5   ag_ratio          570 non-null    int64
 6   sgpt              570 non-null    float64
 7   sgot              570 non-null    float64
 8   alkphos           566 non-null    float64
 9   is_patient        570 non-null    int64
 10  gender_Female     570 non-null    bool
 11  gender_Male       570 non-null    bool
dtypes: bool(2), float64(5), int64(5)
memory usage: 50.1 KB

In [16]:
df.isnull().sum()

age                 0
tot_bilirubin       0
direct_bilirubin    0
tot_proteins        0
albumin             0
ag_ratio            0
sgpt                0
sgot                0
alkphos             4
is_patient          0
gender_Female       0
gender_Male         0
dtype: int64

In [17]:

df["alkphos"] = df["alkphos"].fillna(df["alkphos"].mean())

In [18]:
df.isnull().sum()

age                 0
tot_bilirubin       0
direct_bilirubin    0
tot_proteins        0
albumin             0
ag_ratio            0
sgpt                0
sgot                0
alkphos             0
is_patient          0
gender_Female       0
gender_Male         0
dtype: int64

In [19]:
df.head()

,age,tot_bilirubin,direct_bilirubin,tot_proteins,albumin,ag_ratio,sgpt,sgot,alkphos,is_patient,gender_Female,gender_Male
0,65,0.7,0.1,187,16,18,6.8,3.3,0.90,1,True,False
1,62,10.9,5.5,699,64,100,7.5,3.2,0.74,1,False,True
2,62,7.3,4.1,490,60,68,7.0,3.3,0.89,1,False,True
3,58,1.0,0.4,182,14,20,6.8,3.4,1.00,1,False,True
4,72,3.9,2.0,195,27,59,7.3,2.4,0.40,1,False,True

In [20]:
df=df.astype(int)

In [21]:
df.head()

,age,tot_bilirubin,direct_bilirubin,tot_proteins,albumin,ag_ratio,sgpt,sgot,alkphos,is_patient,gender_Female,gender_Male
0,65,0,0,187,16,18,6,3,0,1,1,0
1,62,10,5,699,64,100,7,3,0,1,0,1
2,62,7,4,490,60,68,7,3,0,1,0,1
3,58,1,0,182,14,20,6,3,1,1,0,1
4,72,3,2,195,27,59,7,2,0,1,0,1

In [22]:
X = df.drop("is_patient", axis=1)
y = df["is_patient"]

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [26]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

/Users/palrpatel/Desktop/practice ml/venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [27]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7456140350877193
              precision    recall  f1-score   support

           1       0.77      0.94      0.85        85
           2       0.50      0.17      0.26        29

    accuracy                           0.75       114
   macro avg       0.63      0.56      0.55       114
weighted avg       0.70      0.75      0.70       114

In [35]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100,  max_depth=10,min_samples_split=5,random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, min_samples_split=5, random_state=42)

In [36]:
y_pred = model.predict(X_test)

In [37]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.7543859649122807

Classification Report:
               precision    recall  f1-score   support

           1       0.80      0.89      0.84        85
           2       0.53      0.34      0.42        29

    accuracy                           0.75       114
   macro avg       0.66      0.62      0.63       114
weighted avg       0.73      0.75      0.74       114

In [31]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Confusion Matrix:
 [[77  8]
 [19 10]]